AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  task-management-app-backend

Globals:
  Function:
    Timeout: 60
Resources:
  ManageTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: src/index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME:
